apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/verjaga/argocd.git
      revision: main
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: apps
      source:
        repoURL: https://github.com/verjaga/argocd.git
        targetRevision: main
        path: '{{path}}'
      destination:
        #name: in-cluster
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
